/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef putin_H
#define putin_H

#include <thrift/TDispatchProcessor.h>
#include "student_types.h"



class putinIf {
 public:
  virtual ~putinIf() {}
  virtual void put(const Student& s) = 0;
};

class putinIfFactory {
 public:
  typedef putinIf Handler;

  virtual ~putinIfFactory() {}

  virtual putinIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(putinIf* /* handler */) = 0;
};

class putinIfSingletonFactory : virtual public putinIfFactory {
 public:
  putinIfSingletonFactory(const boost::shared_ptr<putinIf>& iface) : iface_(iface) {}
  virtual ~putinIfSingletonFactory() {}

  virtual putinIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(putinIf* /* handler */) {}

 protected:
  boost::shared_ptr<putinIf> iface_;
};

class putinNull : virtual public putinIf {
 public:
  virtual ~putinNull() {}
  void put(const Student& /* s */) {
    return;
  }
};

typedef struct _putin_put_args__isset {
  _putin_put_args__isset() : s(false) {}
  bool s;
} _putin_put_args__isset;

class putin_put_args {
 public:

  putin_put_args() {
  }

  virtual ~putin_put_args() throw() {}

  Student s;

  _putin_put_args__isset __isset;

  void __set_s(const Student& val) {
    s = val;
  }

  bool operator == (const putin_put_args & rhs) const
  {
    if (!(s == rhs.s))
      return false;
    return true;
  }
  bool operator != (const putin_put_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const putin_put_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class putin_put_pargs {
 public:


  virtual ~putin_put_pargs() throw() {}

  const Student* s;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class putin_put_result {
 public:

  putin_put_result() {
  }

  virtual ~putin_put_result() throw() {}


  bool operator == (const putin_put_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const putin_put_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const putin_put_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class putin_put_presult {
 public:


  virtual ~putin_put_presult() throw() {}


  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class putinClient : virtual public putinIf {
 public:
  putinClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  putinClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void put(const Student& s);
  void send_put(const Student& s);
  void recv_put();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class putinProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<putinIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (putinProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_put(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  putinProcessor(boost::shared_ptr<putinIf> iface) :
    iface_(iface) {
    processMap_["put"] = &putinProcessor::process_put;
  }

  virtual ~putinProcessor() {}
};

class putinProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  putinProcessorFactory(const ::boost::shared_ptr< putinIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< putinIfFactory > handlerFactory_;
};

class putinMultiface : virtual public putinIf {
 public:
  putinMultiface(std::vector<boost::shared_ptr<putinIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~putinMultiface() {}
 protected:
  std::vector<boost::shared_ptr<putinIf> > ifaces_;
  putinMultiface() {}
  void add(boost::shared_ptr<putinIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void put(const Student& s) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->put(s);
    }
    ifaces_[i]->put(s);
  }

};



#endif
