gflags_example:
	g++ -std=c++11      example.cpp   -o example -I/home/bjliuchang5/study/gflag/gflags/build/include -L/home/bjliuchang5/study/gflag/gflags/build/lib/ -pthread -gflags
clean:
	rm gflags_example

